### DISCUSSION TITLE
How to customize aptos indexer for a particular contract address?

### DISCUSSION THREAD

**Discussion by shivamlync** [aptos-labs/aptos-developer-discussions#141] [Questions]
In the case of the config file for creating a custom indexer on Aptos, below you can find the config file.
```yaml
health_check_port: 8084
server_config:
  processor_config:
    type: user_transaction_processor
  postgres_connection_string: postgresql://postgres:postgres@localhost:5432/test
  indexer_grpc_data_service_address: https://grpc.testnet.aptoslabs.com
  indexer_grpc_http2_ping_interval_in_secs: 60
  indexer_grpc_http2_ping_timeout_in_secs: 10
  number_concurrent_processing_tasks: 10
  starting_version: 
  auth_token: <token>
  transaction_filter:
    focus_user_transactions: true
    focus_contract_addresses:
      - "0x0" # example contract address
```
1. How does the`transaction_filter` parameter work? 
2. I want the data for one of my contract addresses here. How can I achieve that?
3. There is a field called `entry_function_id_str`, I want to use that field to filter out data based on that parameter for one of my contract addresses.  So, can I implement this and get limited data from the indexer? 
4. I would like to have a working example of an indexer where the working of `transaction_filter` is shown which includes `focus_user_transactions` and `focus_contract_addresses` parameters.

@gregnazario  @JohnChangUK  @chiumax  @GotenJBZ  Any suggestions how can I implement the indexer in a efficient manner where the container doesn't stop and if there are any transactions it inserts them into the database and if there aren't any then it keeps on searching but doesn't panics or stops.

**Comment by rtso** [comment]
@shivamlync This is an alpha feature that we recently introduced. The transaction filter criteria are combined with `AND`. If a criteria is not set, it is ignored.
In config.yaml, to use the transaction filter:
```
server_config:
  # This is optional
  transaction_filter:
    # Only allow transactions from these contract addresses
    focus_contract_addresses:
      - "0x0"
    # Skip transactions from these sender addresses
    skip_sender_addresses:
      - "0x0"
    # Skip all transactions that aren't user transactions
    focus_user_transactions: true
```

You can use `focus_contract_addresses` to only allow transactions that come from your entry function.

**Reply by shivamlync** [reply]
Is it possible to provide a working example based on the configuration file

**Reply by shivamlync** [reply]
@rtso is it possible to provide a working example for processor type `user transaction` using the `focus_contract_addresses` parameter.

**Reply by BriungRi** [reply]
I think the team is taking some time to reply because they're already working on a refactor that may better support this feature.

**Reply by shivamlync** [reply]
let me know when I can implement the feature regarding this.

PS: 
```yaml
transaction_filter:
    # Only allow transactions from these contract addresses
    focus_contract_addresses: # this will be used to filter out the transactions made on this contract address
      - "0x0"
    # Skip transactions from these sender addresses
    # skip_sender_addresses:
    # - "0x0"
    # Skip all transactions that aren't user transactions
    focus_user_transactions: true # This one will filter the user transactions only for the above contract address.
```

Feature Request:
- Is it possible to add another parameter called `entry_function_id_str` to limit the data more?

@BriungRi
