### DISCUSSION TITLE
Unable to resolve packages for AptosFramework

### DISCUSSION THREAD

**Discussion by angieyth** [aptos-labs/aptos-developer-discussions#261] [Questions]
### Discord user ID

Amity

### Describe your question in detail.

please am encountering this aptos move compile 

`Compiling, may take a little while to download git dependencies...
FETCHING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
{
  "Error": "Move compilation failed: Unable to resolve packages for package 'akindo': While resolving dependency 'AptosFramework' in package 'akindo': While processing dependency 'AptosFramework': Unable to find package manifest for 'AptosFramework' at \"/home/amityclev/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework\""
}`

### What have you tried or looked at?  Or how can we reproduce the error?

N/A

### Which operating system are you using?

Windows

### Which SDK or tool are you using? (if any)

TypeScript SDK

**Comment by Amity808** [comment]
[package]
name = "waste_manager"
version = "1.0.0"
authors = []

[addresses]
waste_manager = "f32c57475c9c4f083b3ba81e6c03383810fba366af6ca91b74c15d95f9139c41"

# [dev-addresses]
# waste_manager = "f32c57475c9c4f083b3ba81e6c03383810fba366af6ca91b74c15d95f9139c41"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]


yes i have check git disscusion group

window/linux 

when i run aptos move compile i get the above error but i try remix and change the rev= 1.13.1 it work

**Reply by Alexzander-Stone** [reply]
~~Hey there @Amity808, is there a reason why you're targeting `rev = "devnet"`, rather than the default option (where you don't define `rev`)? Something like:~~
```console
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
```


If you could give that a try, and let us know the results, it'll be super useful!

-----

# Proper setup

```console
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
```

**Reply by Amity808** [reply]
Thanks i will try it

**Reply by Alexzander-Stone** [reply]
Hey @Amity808, I misread your dependency setup, initially. I updated to include the `rev` tag, again.

Can you try to compile with `"mainnet"`, and see if there's a resulting error?

**Reply by porkytheblack** [reply]
I run into the same issue. 
here's how I'm setting up the dependancies: 

```toml

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-token-objects/"
rev = "mainnet"
```
