### DISCUSSION TITLE
Env variable in my profile config.yaml

### DISCUSSION THREAD

**Discussion by spielcrypto** [aptos-labs/aptos-developer-discussions#343] [Questions]
### Discord user ID

spielcrypto

### Describe your question in detail.

my profiles config.yaml looks like this:
```yaml
profiles:
  testnet:
    private_key: "MY PRIVATE KEY"
    public_key: "MY PUBLIC KEY"
    account: MY ACCOUNT
    rest_url: "https://fullnode.testnet.aptoslabs.com"
    faucet_url: "https://faucet.testnet.aptoslabs.com"
```

I tried to do this:
```yaml
profiles:
  testnet:
    private_key: ${PRIVATE_KEY}
    public_key: "MY PUBLIC KEY"
    account: MY ACCOUNT
    rest_url: "https://fullnode.testnet.aptoslabs.com"
    faucet_url: "https://faucet.testnet.aptoslabs.com"
```
However doesn't work, when I try to publish a contract I get this error: 
"Unexpected error: profiles.testnet: DeserializationError at line 10 column 12"

even executing with the client in javascript there is not way to pass the yaml config file already rendered with ejs.

Is there anyway to pass env var to the config.yaml? otherwise you need to implement something urgently, expose private key into the file is a high risk for the deployed

### Which operating system are you using?

Linux (Ubuntu, Fedora, Windows WSL, etc.)

### Which SDK or tool are you using? (if any)

Aptos CLI

### Describe your environment or tooling in detail

aptos-move 3.4.1
