### DISCUSSION TITLE
How do I call a function in a different Move module / smart contract?

### DISCUSSION THREAD

**Discussion by banool** [aptos-labs/aptos-developer-discussions#36] [Questions] [answered]
[Originally from Stack Overflow](https://stackoverflow.com/q/74640493/3846032).

I know there is a Move module (smart contract) on chain with a function that looks like this:
```rust
public entry fun do_nothing() {}
```
I know it is deployed at `6286dfd5e2778ec069d5906cd774efdba93ab2bec71550fa69363482fbd814e7::other::do_nothing`. You can see the module in the explorer [here](https://explorer.aptoslabs.com/account/0x6286dfd5e2778ec069d5906cd774efdba93ab2bec71550fa69363482fbd814e7/modules).

I have a Move module of my own that looks like this.

`Move.toml`:
```toml
[package]
name = 'mine'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
my_addr = "81e2e2499407693c81fe65c86405ca70df529438339d9da7a6fc2520142b591e"
other_addr = "6286dfd5e2778ec069d5906cd774efdba93ab2bec71550fa69363482fbd814e7"
```

`sources/mine.move`:
```rust
module my_addr::mine {
    use other_addr::other::do_nothing;

    public entry fun do_stuff() {
        do_nothing();
    }
}
```

As you can see, I'm telling the compiler where the `other` module is by setting `other_addr = "6286dfd5e2778ec069d5906cd774efdba93ab2bec71550fa69363482fbd814e7"`. However, when I try to compile my Move module, it fails, saying "unbound module", meaning it doesn't know what the "other" module is.

```
$ aptos move compile --named-addresses my_addr="`yq .profiles.default.account < .aptos/config.yaml`"
Compiling, may take a little while to download git dependencies...
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING mine
error[E03002]: unbound module
  ┌─ /Users/dport/github/move-examples/call_other_module/mine/sources/mine.move:2:9
  │
2 │     use other_addr::other::do_nothing;
  │         ^^^^^^^^^^^^^^^^^ Invalid 'use'. Unbound module: '(other_addr=0x6286DFD5E2778EC069D5906CD774EFDBA93AB2BEC71550FA69363482FBD814E7)::other'

error[E03005]: unbound unscoped name
  ┌─ /Users/dport/github/move-examples/call_other_module/mine/sources/mine.move:5:9
  │
5 │         do_nothing();
  │         ^^^^^^^^^^ Unbound function 'do_nothing' in current scope

{
  "Error": "Move compilation failed: Compilation error"
}
```

Why is compilation failing? Why can't the compiler figure it out for me based on the ABIs of the Move modules it finds at `other_addr` on chain?
