### DISCUSSION TITLE
How to transfer Fungible Assets via Python?

### DISCUSSION THREAD

**Discussion by sellmon** [aptos-labs/aptos-developer-discussions#630] [Questions] [answered]
### Describe your question in detail.

Hi, I need help with creating a transaction (tx) for transferring FA. Here's the code:
```
async def send_fa(sender_key="0x..., receiver="0x...", amount=100):
    sender = Account.load_key(str(sender_key))

    try:
        logger.info("Send USDT FA")

        payload = EntryFunction.natural(
            "0x1::aptos_account",
            "transfer_fungible_assets",
            [],
            [
                TransactionArgument(sender, Serializer.struct),
                TransactionArgument(StructTag.from_str("0x1::object::Object<0x357b0b74bc833e95a115ad22604854d6b0fca151cecd94111770e5d6ffc9dc2b>")),
                TransactionArgument(AccountAddress.from_str(receiver), Serializer.struct),
                TransactionArgument(amount, Serializer.u64),
            ],
        )

        transaction = await rest_client.create_bcs_signed_transaction(sender, TransactionPayload(payload))
        txn_hash = await rest_client.submit_bcs_transaction(transaction)
        await rest_client.wait_for_transaction(txn_hash)

        return txn_hash
```

I've tried different variants, but I can’t understand how to do it via Python. In TypeScript, everything works fine, but I need it in Python for my case.

### Which operating system are you using?

macOS

### Which SDK or tool are you using? (if any)

Python SDK

**Comment by 0x-j** [comment]
what error are you running into? we have some python sdk example in https://github.com/aptos-labs/aptos-python-sdk/tree/main/examples

**Reply by sellmon** [reply]
I tried this one

```python
async def transfer_fungible_assets(sender_key=WALLET, amount=100):
    sender = Account.load_key(str(sender_key))

    payload = TransactionPayload(
        EntryFunction.natural(
            "0x1::aptos_account",
            "transfer_fungible_assets",
            [],
            [
                TransactionArgument(AccountAddress.from_str("0x357b0b74bc833e95a115ad22604854d6b0fca151cecd94111770e5d6ffc9dc2b"), Serializer.struct),
                TransactionArgument(AccountAddress.from_str("0x..."), Serializer.struct),
                TransactionArgument(amount, Serializer.u64),
            ],
        )
    )

    transaction = await rest_client.create_bcs_transaction(sender, payload)
    print(transaction)

    simulation = await rest_client.simulate_transaction(transaction, sender)
    logger.debug(f"{(simulation[0].get('payload'),)} Simulation: {simulation[0].get('vm_status')}")
    return simulation
```

And got this answer:

```
DEBUG    | ({'function': '0x1::aptos_account::transfer_fungible_assets', 'type_arguments': [], 'arguments': [{'inner': '0x357b0b74bc833e95a115ad22604854d6b0fca151cecd94111770e5d6ffc9dc2b'}, '0x...', '100'], 'type': 'entry_function_payload'},) Simulation: Move abort in 0x1::fungible_asset: EINSUFFICIENT_BALANCE(0x10004): Insufficient balance to withdraw or transfer.
```

```
RawTransaction:
    sender: 0x...
    sequence_number: 790
    payload: 0x1::aptos_account::transfer_fungible_assets::<[]>([b'5{\x0bt\xbc\x83>\x95\xa1\x15\xad"`HT\xd6\xb0\xfc\xa1Q\xce\xcd\x94\x11\x17p\xe5\xd6\xff\xc9\xdc+', b'@\xad\x87\xd3\xa1n\x88\xf1\x97\xe5\xa2\x8f\x87U\xb7f\xe1\xceS\x0e\xaf\xdb\xf4;\x97\x18\xdf\xa4"\xac\xba\xab', b'd\x00\x00\x00\x00\x00\x00\x00'])
    max_gas_amount: 100
    gas_unit_price: 100
    expiration_timestamps_secs: 1741634619
    chain_id: 1
```

I have enough balance on address and different gas didn't help
