### DISCUSSION TITLE
Issue with For loop compilation

### DISCUSSION THREAD

**Discussion by gregnazario** [aptos-labs/aptos-developer-discussions#65] [Questions] [answered]
From lollobene on Discord:

hey guys, I'm trying to compile using devnet git dependencies like this in Move.toml:
```toml
[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
```

and getting this error:
```shell
error[E01002]: unexpected token
    ┌─ /Users/lollobene/.move/https___github_com_aptos-labs_aptos-core_git_devnet/aptos-move/framework/aptos-framework/sources/randomness.move:520:16
    │
520 │         for (i in 0..n) {
    │             -  ^ Expected ')'
    │             │   
    │             To match this '('

{
  "Error": "Move compilation failed: Compilation error"
}
```
