### DISCUSSION TITLE
Is there a way to connect a Validator to a VFN and not the other way around?

### DISCUSSION THREAD

**Discussion by TesodeAll** [aptos-labs/aptos-developer-discussions#687] [Questions]
### Discord user ID

tesode

### Describe your question in detail.

We are trying it with the following configuration but it doesn't seem to work:

Validator:
```
full_node_networks:
  - network_id: "vfn"
    listen_address: "/ip4/0.0.0.0/tcp/6181"
    seeds:
      00000000000000000000000000000000d58bc7bb154b38039bc9096ce04e1237:
        addresses:
        - "/ip4/X.X.X.X/tcp/6181/noise-ik/f0274c2774519281a8332d0bb9d8101bd58bc7bb154b38039bc9096ce04e1237/handshake/0"
        role: "ValidatorFullNode"
```
VFN:
```
full_node_networks:
  - network_id: "vfn"
    listen_address: "/ip4/0.0.0.0/tcp/6181"
    identity:
      type: "from_config"
      key: "XXXXXXXXXXXXXXXXXX"
      peer_id: "00000000000000000000000000000000d58bc7bb154b38039bc9096ce04e1237"
```

### Which operating system are you using?

Linux (Ubuntu, Fedora, Windows WSL, etc.)

### Which SDK or tool are you using? (if any)

N/A
