### DISCUSSION TITLE
aptos archive node setup

### DISCUSSION THREAD

**Discussion by riprsa** [aptos-labs/aptos-developer-discussions#689] [General]
hi, i downloaded archive from genesis on my server, now i have a really big archive. how do i do from now? should i unarchive it before running the node? i am a bit lost

there should be fullnode.yaml with

```yaml
base:
  role: "full_node"
  data_dir: "/opt/aptos/data"
...
```
 
so, /opt/aptos/data is unarchived data from s3 storage, or just the archive? i am afraid to try it, because do not want to corrupt the ledger data
